 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: roadrunner-deployment
   labels:
     app: roadrunner
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: roadrunner
   template:
     metadata:
       labels:
         app: roadrunner
     spec:
       containers:
       - image: kaiomagalhaes/roadrunner:v1.111.0
         name: roadrunner
         ports:
           - containerPort: 5000
         env:
         - name: DATABASE_URL
           valueFrom:
             secretKeyRef:
               name: roadrunner-secret
               key: db-host
         - name: LOG_HOST
           value: "test-roadrunner-k8s"
         - name: LOG_HOST
           value: "qa"
