apiVersion: v1
kind: Secret
metadata:
  name: roadrunner-secret
type: Opaque
data:
  db-host: cG9zdGdyZXM6Ly9jZ2duc3J3Z2ZqenZ3azphZWI3Zjk4YTI5Zjc5NjFlYzdmZjY0YzU1ZjU1ZjdhYzc3OGYzMDUxN2I5ZDI3NjQ3Y2JhZTg1MmM1YjA3OWQ3QGVjMi0zNC0xOTctMTg4LTE0Ny5jb21wdXRlLTEuYW1hem9uYXdzLmNvbTo1NDMyL2RkZGU5ZXFlMjkyYjY0
  slack-api-key: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuY205aFpISjFibTVsY2cuMlJDSklTNXJXN29nZ2p6Z0N2dTF4R3J4M2UwaEJFLTN6U3JhaUxVYTFlWQ==
  github-auth-key: Z2hwX2VXbzhyYjFQMmxnbXNTSUlZQ1VybGs3UHZmRXJlZTNJd1lBUA==

---
apiVersion: v1
kind: Secret
metadata:
  name: notifications-secret
type: Opaque
data:
  slack-api-key: eG94Yi0yMzMwMzI2NTk2LTkxNjQzNDI2MjU5OC11N2JZMUd3RkVITWZlZkxlOWtjTDR5UDc=
  authentication-key: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuY205aFpISjFibTVsY2cuMlJDSklTNXJXN29nZ2p6Z0N2dTF4R3J4M2UwaEJFLTN6U3JhaUxVYTFlWQ==